### PR TITLE
Add validation tools, an sqlite3 database, and fix data

### PR DESCRIPTION
**Pull request by mindfilleter**
Objective:
The primary objective of this commit is to provide an SQL interface querying the Starfield data. This enables users to take advantage of SQL to either directly query the data for what they're looking for, or to build apps/tooling on top of this work for other purposes.

Details:
This commit adds 2 scripts (create_db.py, restructure.py).

restructure.py reads the starfield_data_updated.json file, validates it, and then stores the data in a flattened format in galaxy.json.

create_db.py takes the galaxy.json output of restructure.py and inserts the data into a sqlite3 database file.

### CODE REVIEW

**Comment by mindfilleter** [comment]
Hey there! Sorry for the commit bomb. Thank you so much for putting this project together. I added some utility for my own purposes and am happy to contribute back to your repo if you're so inclined.

**Comment by Adanessa** [comment]
Hi!
I am so happy if my work came to use and honored to have you add to it!
I have also been collecting a lot more data but I have not bothered to put
it into the repository since I did not think that anyone would need or use
it.
Later today I will ask my friend to help me put some of these changes into
the main branch. Also I can add the rest of my data. Maybe there are more
things you or someone else could use there.
My current project is to use all the data in my website, but I'm new to
coding, sql, django, html, css and everything else so it might take
some time for me to finish it.
At least I've gotten most of it up to my down supabase at this point and in
a month or so I might be able to publish a rough version of the site.

Feel free to take a look at the django project if you want to see the
status of it, https://github.com/Adanessa/starfieldwebz.

Big thanks again for taking your time!

**Comment by Adanessa** [comment]
Oh and if you do look into the django project, please keep in mind that the
current status of it is crap, i'm just trying to learn how it works.

**Comment by mindfilleter** [comment]
Hey no worries. We all start somewhere. The data you gathered is super helpful. What I'm working on are programmatic solutions for problems that would be very time consuming to solve manually. Here's an example:

Is there one system where every common extractable/domesticable resource is available with hab rank 0? If so, which system and which planets do I get which resources from?

It's a common question but it would take you hours of flying around checking systems and manually crossing off checklists to answer this question. You can get pretty close to the solutions by using the system database at inara.cz (https://inara.cz/starfield/starsystems/) but you can't filter on exctractable/domesticable resources only.

Besides, this data doesn't change that frequently so with local access to everything I can jam it all into a mobile app or something and not require an internet connection for it.

**Comment by Adanessa** [comment]
Oh it sounds like what I actually wanted to do from the start. I then
noticed how much data I needed for it so that forced me to learn web
scraping.
My idea is to have a way to search for the ideal set of planets for outpost
building. The user will be able to input specific details, such as hab
rank, zoology, surveying and other skills that enable buildings.
Users will also be able to enter if it wants specific/all crafted
materials. There is more stuff to this but I can't remember them all. In
the end it's only one thing that I'm missing, and I'm not sure how to get
that
without reverse-engineering the entire game(which I can't). And that is to
be able to know how many outposts you might need to collect all resources
from one planet.  Let's say a planet has iron aluminium beryllium and he-3.
How can I know how many outposts that would be needed to collect all of
those on one planet? He-3 is usually collected at the north and south
poles, Iron might not be close enough to get that at the same time right?
I have been looking into the material "families" to see if that makes it
clear. However I've spent 1 hour on 3 different planets trying to build
outposts at the very border of biomes but it does not seem to be 100%
accurate.

Do you have any ideas about this?

I might have two rough scripts that could assist if you want. Very rough.
If so I'll see if I can find them.

**Comment by mindfilleter** [comment]
I don't think we can solve that without reverse engineering the terrain generation, which is well beyond the scope of effort I'm willing to put into this. ha ha ha

Really I just want to reduce the millions of possibilities down to a handful of probabilities. I don't mind playing the game and trying to make it work if I know it *could* work. As opposed to praying that it *might* work. If you take my meaning.

**Comment by Adanessa** [comment]
You are very correct. I only intended to do a simple small script for
myself, it got out of hand. So now I haven't even played the game for 3
months.  Anyway I'll be off your back now. After including your code I'll
upload the rest of the data, maybe you can use that for future projects!
Again, I'm very grateful that you took your time to improve the project.

Have a great day now!

**Review by Adanessa — APPROVED** [review]

**Pull request merged**
